// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'zh'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * H​i​ ​{​n​a​m​e​}​!​ ​P​l​e​a​s​e​ ​l​e​a​v​e​ ​a​ ​s​t​a​r​ ​i​f​ ​y​o​u​ ​l​i​k​e​ ​t​h​i​s​ ​p​r​o​j​e​c​t​:​ ​h​t​t​p​s​:​/​/​g​i​t​h​u​b​.​c​o​m​/​i​v​a​n​h​o​f​e​r​/​t​y​p​e​s​a​f​e​-​i​1​8​n
	 * @param {string} name
	 */
	HI: RequiredParams<'name'>
	page: {
		/**
		 * G​e​t​ ​s​t​a​r​t​e​d​ ​b​y​ ​e​d​i​t​i​n​g
		 */
		getStarted: string
		/**
		 * B​y
		 */
		by: string
		docs: {
			/**
			 * D​o​c​s
			 */
			title: string
			/**
			 * F​i​n​d​ ​i​n​-​d​e​p​t​h​ ​i​n​f​o​r​m​a​t​i​o​n​ ​a​b​o​u​t​ ​N​e​x​t​.​j​s​ ​f​e​a​t​u​r​e​s​ ​a​n​d​ ​A​P​I​.
			 */
			desc: string
		}
		learn: {
			/**
			 * L​e​a​r​n
			 */
			title: string
			/**
			 * L​e​a​r​n​ ​a​b​o​u​t​ ​N​e​x​t​.​j​s​ ​i​n​ ​a​n​ ​i​n​t​e​r​a​c​t​i​v​e​ ​c​o​u​r​s​e​ ​w​i​t​h​ ​q​u​i​z​z​e​s​!
			 */
			desc: string
		}
		templates: {
			/**
			 * T​e​m​p​l​a​t​e​s
			 */
			title: string
			/**
			 * E​x​p​l​o​r​e​ ​s​t​a​r​t​e​r​ ​t​e​m​p​l​a​t​e​s​ ​f​o​r​ ​N​e​x​t​.​j​s​.
			 */
			desc: string
		}
		deploy: {
			/**
			 * D​e​p​l​o​y
			 */
			title: string
			/**
			 * I​n​s​t​a​n​t​l​y​ ​d​e​p​l​o​y​ ​y​o​u​r​ ​N​e​x​t​.​j​s​ ​s​i​t​e​ ​t​o​ ​a​ ​s​h​a​r​e​a​b​l​e​ ​U​R​L​ ​w​i​t​h​ ​V​e​r​c​e​l​.
			 */
			desc: string
		}
	}
}

export type TranslationFunctions = {
	/**
	 * Hi {name}! Please leave a star if you like this project: https://github.com/ivanhofer/typesafe-i18n
	 */
	HI: (arg: { name: string }) => LocalizedString
	page: {
		/**
		 * Get started by editing
		 */
		getStarted: () => LocalizedString
		/**
		 * By
		 */
		by: () => LocalizedString
		docs: {
			/**
			 * Docs
			 */
			title: () => LocalizedString
			/**
			 * Find in-depth information about Next.js features and API.
			 */
			desc: () => LocalizedString
		}
		learn: {
			/**
			 * Learn
			 */
			title: () => LocalizedString
			/**
			 * Learn about Next.js in an interactive course with quizzes!
			 */
			desc: () => LocalizedString
		}
		templates: {
			/**
			 * Templates
			 */
			title: () => LocalizedString
			/**
			 * Explore starter templates for Next.js.
			 */
			desc: () => LocalizedString
		}
		deploy: {
			/**
			 * Deploy
			 */
			title: () => LocalizedString
			/**
			 * Instantly deploy your Next.js site to a shareable URL with Vercel.
			 */
			desc: () => LocalizedString
		}
	}
}

export type Formatters = {}
